config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "marketing#new"
  post "/sent_mail", to: "marketing#sent_mail"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    require 'csv'
end

app/controllers/marketing_controller.rb
class MarketingController < ApplicationController
    def new
    end

    def sent_mail
        uploaded_file = params[:csv_file]

        if uploaded_file.present?
            csv_data = CSV.read(uploaded_file.path)
            @csv_records = csv_data.drop(1)  # Skip the header row
            puts("===> @csv_records: ", @csv_records)
            redirect_to root_path

            # Now @csv_records contains an array of arrays where each inner array represents a row from the CSV file
        else
            flash[:error] = "Please select a CSV file to upload."
            redirect_to root_path
        end

        # redirect_to root_path
        # MarketingMailer.send_mail.deliver_later
        # MarketingMailer.with(order: @order).send_mail.deliver_laterr
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketing Mail</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <style>
      body{
        padding:60px;
      }

      form{
        width: 100%;
        padding:50px;
        background:whitesmoke;
        border-radius:5px;
      }

      .card-footerrr {
        padding: 0.75rem 1.25rem;
      }

    </style>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/marketing/new.html.erb
<form action="<%= sent_mail_path %>" method="post" enctype="multipart/form-data">
    <div class="card-body">
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Upload CSV File<span style="color: red;">*</span></label>
            <div class="col-sm-10">
                <input type="file" name="csv_file" class="form-control" accept=".csv" required>
            </div>
        </div>
    </div>
    <div class="card-footerrr">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>